name: Send Log

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Send log
        run: |
          curl -v -X POST \
            -H "Authorization: Splunk ${{6c976103-9cc8-4af2-bd9b-7a846afff787}}" \
            -H "Content-Type: application/json" \
            -d '{"message":"Hello from GitHub Actions"}' \
            http://5d43081f.in.prod.onum.com:9443/services/collector
